---
  # Ansible and NFS Storage
  - name: toolbox
    ip:   192.168.2.201
    memory: 1024
    cpus: 1

    disks:
      - name: exports
        size: 100

    provisions:
     - type: file
       src: ansible
       dest: /vagrant/ansible

     - type: shell
       script: shell/setup_ansible.sh
       args:

     - type: shell
       script: shell/create_disk_partition.sh
       args: --disk "/dev/sdc" --label "msdos" --type "primary" --start "0" --end "100%" --fs "ext4"

     - type: shell
       script: shell/disk_mount.sh
       args: --disk "/dev/sdc1" --dest "/exports"

  # Cluster Master
  - name: master
    ip:   192.168.2.205
    memory: 4096
    cpus: 2

    disks:
      - name: docker
        size: 15

  # Docker Register, and HA Proxy
  - name: infra
    ip:   192.168.2.210
    memory: 4096
    cpus: 2

    disks:
      - name: docker
        size: 20

  # Worker node1
  - name: node1
    ip:   192.168.2.211
    memory: 12288
    cpus: 4

    disks:
      - name: docker
        size: 40

  # Worker node2
  - name: node2
    ip:   192.168.2.212
    memory: 12288
    cpus: 4

    disks:
      - name: docker
        size: 40

  # Worker node3
  - name: node3
    ip:   192.168.2.213
    memory: 12288
    cpus: 4

    disks:
      - name: docker
        size: 40
