---

- name: Openshift Pre Installation
  hosts: cluster
  become: yes
  
  tasks:        
    - name: Install OpenShift Repositories on All Nodes
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - centos-release-openshift-origin311
        - epel-release
    
    - name: List Repositories
      command: yum repolist
      register: yum_out
    - debug:
        var: yum_out.stdout_lines
    
    - name: Install OpenShift Utils on Ansible Machine
      when: inventory_hostname in groups.ansible
      yum:
        name: openshift-ansible
        state: latest
        