##=============================================================================
# Ansible groups
##=============================================================================
[ansible]
toolbox.ocp3.local.net

[masters]
master.ocp3.local.net

[etcd]
master.ocp3.local.net

[infra]
infra.ocp3.local.net

#[admin]
#metrics.ocp3.local.net

[app]
node1.ocp3.local.net
node2.ocp3.local.net

#[glusterfs]
#gluster1.ocp3.local.net glusterfs_devices='[ "/dev/sdb" ]'

[nfs]
toolbox.ocp3.local.net

[nodes]
master.ocp3.local.net   openshift_node_group_name="node-config-master"
infra.ocp3.local.net    openshift_node_group_name="node-config-infra"
node1.ocp3.local.net    openshift_node_group_name="node-config-compute"
node2.ocp3.local.net    openshift_node_group_name="node-config-compute"

[OSEv3:children]
masters
etcd
nodes
#glusterfs
nfs

[cluster:children]
ansible
nodes
#glusterfs
nfs

##=============================================================================
# Common/Required configuration variables
##=============================================================================

[OSEv3:vars]
ansible_ssh_user=root
debug_level=4

openshift_deployment_type=origin
system_images_registry="docker.io"
openshift_release="3.11"
openshift_image_tag=v3.11.0
openshift_pkg_version=-3.11.0

# Skip memory and disk check
openshift_disable_check=docker_image_availability,docker_storage,disk_availability,memory_availability

#openshift_master_cluster_method=native
openshift_master_cluster_hostname=master.ocp3.local.net
openshift_master_cluster_public_hostname=master.ocp3.local.net

os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
#osm_cluster_network_cidr=12.128.0.0/14
#openshift_portal_net=174.30.0.0/16

openshift_master_default_subdomain=apps.ocp3.local.net

#openshift_use_dnsmasq=False
#openshift_node_dnsmasq_additional_config_file=/home/bob/ose-dnsmasq.conf

# Configure Security
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]
#openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

# default project node selector
osm_default_node_selector='node-role.kubernetes.io/compute=true'

# GlusterFS
#openshift_storage_glusterfs_is_native=false
#openshift_storage_glusterfs_storageclass=true
#openshift_storage_glusterfs_heketi_is_native=false
#openshift_storage_glusterfs_heketi_url=gluster1.ocp3.local.net
#openshift_storage_glusterfs_heketi_executor=ssh
#openshift_storage_glusterfs_heketi_ssh_port=22
#openshift_storage_glusterfs_heketi_ssh_user=root
#openshift_storage_glusterfs_heketi_ssh_sudo=false
#openshift_storage_glusterfs_heketi_ssh_keyfile="/root/.ssh/id_rsa"
#
#openshift_master_dynamic_provisioning_enabled=true


# Configure Router
openshift_router_selector='node-role.kubernetes.io/infra=true'
openshift_hosted_router_replicas=1
openshift_hosted_router_extended_validation=true
#openshift_hosted_router_certificate={\"certfile\": \"/path/to/router.crt\", \"keyfile\": \"/path/to/router.key\", \"cafile\": \"/path/to/router-ca.crt\"}

# Configure Registry
openshift_registry_selector='node-role.kubernetes.io/infra=true'
openshift_hosted_registry_replicas=1

openshift_enable_unsupported_configurations=true

openshift_hosted_registry_storage_kind=nfs
openshift_hosted_registry_storage_access_modes=['ReadWriteMany']
openshift_hosted_registry_storage_host=toolbox.ocp3.local.net
openshift_hosted_registry_storage_nfs_directory=/exports
openshift_hosted_registry_storage_volume_name=registry
openshift_hosted_registry_storage_volume_size=10Gi

# Configure Logging
#openshift_logging_install_logging=true
#openshift_hosted_logging_elasticsearch_cluster_size=1
#openshift_logging_es_cluster_size=1
#openshift_logging_storage_kind=nfs
#openshift_logging_storage_access_modes=['ReadWriteOnce']
#openshift_logging_storage_host=nfs.ocp3.local.net
#openshift_logging_storage_nfs_directory=/exports
#openshift_logging_storage_volume_name=logging
#openshift_logging_storage_volume_size=10Gi
#openshift_logging_es_nodeselector={'function': 'logging'}
#openshift_logging_kibana_nodeselector={'function': 'logging'}
#openshift_logging_curator_nodeselector={'function': 'logging'}

# Configure Metrics
#openshift_metrics_install_metrics=true
#openshift_metrics_server_install=true
#openshift_metrics_storage_kind=nfs
#openshift_metrics_storage_access_modes=['ReadWriteOnce']
#openshift_metrics_storage_host=toolbox.ocp3.local.net
#openshift_metrics_storage_nfs_directory=/exports
#openshift_metrics_storage_volume_name=metrics
#openshift_metrics_storage_volume_size=15Gi
#openshift_metrics_cassandra_nodeselector={'function': 'metrics'}
#openshift_metrics_hawkular_nodeselector={'function': 'metrics'}
#openshift_metrics_heapster_nodeselector={'function': 'metrics'}


# Configure Prometheus and Grafana
#openshift_hosted_prometheus_deploy=true

#openshift_prometheus_storage_kind=nfs
#openshift_prometheus_alertmanager_storage_kind=nfs
#openshift_prometheus_alertbuffer_storage_kind=nfs

#openshift_prometheus_storage_type=pvc
#openshift_prometheus_alertmanager_storage_type=pvc
#openshift_prometheus_alertbuffer_storage_type=pvc

#openshift_prometheus_node_selector={'function': 'metrics'}

#openshift_hosted_grafana_deploy=true
#openshift_grafana_node_exporter=true
#openshift_grafana_storage_type=pvc
#openshift_grafana_sc_name=
#openshift_grafana_node_selector={'function': 'metrics'}


# Configure Management
#openshift_management_install_management=true
#openshift_management_app_template=miq-template
#openshift_management_template_parameters={'APPLICATION_VOLUME_CAPACITY': '10Gi', 'DATABASE_VOLUME_CAPACITY': '25Gi'}
#openshift_management_template_parameters={'APPLICATION_MEM_REQ': '3000Mi', 'POSTGRESQL_MEM_REQ': '1Gi', 'ANSIBLE_MEM_REQ': '512Mi'}
#
#openshift_management_storage_class=nfs
#openshift_management_storage_nfs_local_hostname=nfs.ocp3.local.net
#openshift_management_storage_nfs_base_dir=/exports
#
#openshift_management_nodeselector={'function': 'mgmt'}
