##=============================================================================
# Ansible groups
##=============================================================================
[ansible]
toolbox.ocp3.local.net

[masters]
master.ocp3.local.net

[etcd]
master.ocp3.local.net

[infra]
infra.ocp3.local.net

#[admin]
#metrics.ocp3.local.net

[app]
node1.ocp3.local.net
node2.ocp3.local.net

#[glusterfs]
#gluster1.ocp3.local.net glusterfs_devices='[ "/dev/sdb" ]'

[nfs]
toolbox.ocp3.local.net

[nodes]
master.ocp3.local.net   openshift_public_ip=192.168.2.205    openshift_node_group_name="node-config-master"
infra.ocp3.local.net    openshift_public_ip=192.168.2.210    openshift_node_group_name="node-config-infra"
node1.ocp3.local.net    openshift_public_ip=192.168.2.211    openshift_node_group_name="node-config-compute"
node2.ocp3.local.net    openshift_public_ip=192.168.2.212    openshift_node_group_name="node-config-compute"

[OSEv3:children]
masters
etcd
nodes
#glusterfs
nfs

[cluster:children]
ansible
nodes
#glusterfs
nfs

##=============================================================================
# Common/Required configuration variables
##=============================================================================

[OSEv3:vars]
ansible_ssh_user=root
debug_level=4

openshift_deployment_type=origin
system_images_registry="docker.io"
openshift_release="3.11"
openshift_image_tag=v3.11.0
openshift_pkg_version=-3.11.0

# Skip memory and disk check
openshift_disable_check=docker_image_availability,docker_storage,disk_availability,memory_availability

#openshift_master_cluster_method=native
openshift_master_cluster_hostname=master.ocp3.local.net
openshift_master_cluster_public_hostname=master.ocp3.local.net

os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
#osm_cluster_network_cidr=12.128.0.0/14
#openshift_portal_net=174.30.0.0/16

openshift_master_default_subdomain=apps.ocp3.local.net

openshift_console_install=true
openshift_console_hostname=console.apps.ocp3.local.net

#openshift_use_dnsmasq=False
#openshift_node_dnsmasq_additional_config_file=/home/bob/ose-dnsmasq.conf

# Configure Security
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]
#openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

# default project node selector
osm_default_node_selector='node-role.kubernetes.io/compute=true'

# GlusterFS
#openshift_storage_glusterfs_is_native=false
#openshift_storage_glusterfs_storageclass=true
#openshift_storage_glusterfs_heketi_is_native=false
#openshift_storage_glusterfs_heketi_url=gluster1.ocp3.local.net
#openshift_storage_glusterfs_heketi_executor=ssh
#openshift_storage_glusterfs_heketi_ssh_port=22
#openshift_storage_glusterfs_heketi_ssh_user=root
#openshift_storage_glusterfs_heketi_ssh_sudo=false
#openshift_storage_glusterfs_heketi_ssh_keyfile="/root/.ssh/id_rsa"
#
#openshift_master_dynamic_provisioning_enabled=true

##=============================================================================
# Configure Router
##=============================================================================
openshift_hosted_router_selector='node-role.kubernetes.io/infra=true'
openshift_hosted_router_replicas=1
openshift_hosted_router_extended_validation=true
#openshift_hosted_router_certificate={\"certfile\": \"/path/to/router.crt\", \"keyfile\": \"/path/to/router.key\", \"cafile\": \"/path/to/router-ca.crt\"}

##=============================================================================
# Configure Registry
##=============================================================================
openshift_hosted_registry_selector='node-role.kubernetes.io/infra=true'
openshift_hosted_registry_replicas=1

openshift_enable_unsupported_configurations=true

openshift_hosted_registry_storage_kind=nfs
openshift_hosted_registry_storage_access_modes=['ReadWriteMany']
openshift_hosted_registry_storage_host=toolbox.ocp3.local.net
openshift_hosted_registry_storage_nfs_directory=/exports
openshift_hosted_registry_storage_volume_name=registry
openshift_hosted_registry_storage_volume_size=10Gi

##=============================================================================
# Configure Logging
##=============================================================================
openshift_logging_install_logging=false
openshift_logging_es_cluster_size=1
openshift_logging_es_nodeselector={"node-role.kubernetes.io/compute":"true"}
openshift_logging_es_cpu_limit=2
openshift_logging_es_memory_limit=4Gi

openshift_logging_curator_default_days=2
openshift_logging_curator_run_hour=0
openshift_logging_curator_run_minute=0

# Default storage class
openshift_logging_es_pvc_dynamic=true
#openshift_logging_es_pvc_storage_class_name=
openshift_logging_es_pvc_size=10Gi

#openshift_logging_storage_kind=nfs
#openshift_logging_storage_access_modes=['ReadWriteOnce']
#openshift_logging_storage_host=toolbox.ocp3.local.net
#openshift_logging_storage_nfs_directory=/exports
#openshift_logging_storage_volume_name=logging
#openshift_logging_storage_volume_size=10Gi
#openshift_logging_storage_labels={'storage': 'logging'}

##=============================================================================
# Configure Metrics (Hawkular, Cassandra, Heapster)
##=============================================================================
openshift_metrics_install_metrics=false
openshift_metrics_server_install=true
# 2 days
openshift_metrics_duration=2
# Storage Options
openshift_metrics_cassandra_storage_type=dynamic
openshift_metrics_cassandra_pvc_size=10Gi

#openshift_metrics_storage_kind=nfs
#openshift_metrics_storage_access_modes=['ReadWriteOnce']
#openshift_metrics_storage_host=toolbox.ocp3.local.net
#openshift_metrics_storage_nfs_directory=/exports
#openshift_metrics_storage_volume_name=metrics
#openshift_metrics_storage_volume_size=10Gi
#openshift_metrics_storage_labels={'storage': 'metrics'}

##=============================================================================
# Configure monitoring (Prometheus, Grafana)
##=============================================================================
openshift_cluster_monitoring_operator_install=false
openshift_cluster_monitoring_operator_node_selector={"node-role.kubernetes.io/compute":"true"}
openshift_cluster_monitoring_operator_prometheus_storage_capacity="10Gi"
openshift_cluster_monitoring_operator_alertmanager_storage_capacity="2Gi"

# Use external storage
openshift_cluster_monitoring_operator_prometheus_storage_enabled=true
openshift_cluster_monitoring_operator_alertmanager_storage_enabled=true

# Keep commented to use default storage class
#openshift_cluster_monitoring_operator_prometheus_storage_class_name=""
#openshift_cluster_monitoring_operator_alertmanager_storage_class_name=""

openshift_cluster_monitoring_operator_crd_retries=30
openshift_cluster_monitoring_operator_crd_delay=30
